version: '3.4'

services:
  my.ddd.cqrs.temp6.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  local.azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
      
  local.mariadb:
    ports:
      - "3308:3308"
    environment:
      - MYSQL_TCP_PORT=3308
      - MYSQL_ROOT_PASSWORD=example
      ## Creation de la db au lancement du container
      #- MYSQL_DATABASE=mydddcqrstemp6_db
      ## Auth
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=password
    volumes:
    - dbvolume:/var/lib/mysql

volumes:
  dbvolume: