version: '3.4'

services:
  my.ddd.cqrs.temp6.api:
    image: ${DOCKER_REGISTRY-ginsem/}mydddcqrstemp6api
    container_name: mydddcqrstemp6api
    depends_on:
    - local.azurite
    - local.mariadb
    build:
      context: .
      dockerfile: My.DDD.CQRS.Temp6.Api/Dockerfile
    networks:
    - backend_net

  my.ddd.cqrs.temp6.workservice:
    image: ${DOCKER_REGISTRY-ginsem/}mydddcqrstemp6workservice
    build:
      context: .
      dockerfile: My.DDD.CQRS.Temp6.WorkService/Dockerfile
    restart: always
    container_name: mydddcqrstemp6workservice
    depends_on:
    - my.ddd.cqrs.temp6.api
    networks:
    - backend_net
      
  local.azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: localazurite
    command:
      - "azurite"
      - "--queueHost"
      - "0.0.0.0"
      - "--blobHost"
      - "0.0.0.0"
      - "--tableHost"
      - "0.0.0.0"
      - "--disableProductStyleUrl"
    networks:
    - backend_net
      
  local.mariadb:
    image: mariadb:10.5
    container_name: localmariadb
    restart: always
    command:
    - "--port"
    - "3308"
    networks:
    - backend_net
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
    - local.mariadb
    networks:
    - backend_net

  setup:
    build:
      context: .
      dockerfile: elk-conf/setup/Dockerfile
    container_name: setup
    init: true
    env_file:
    - .env
    networks:
      - backend_net
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    env_file:
    - .env
    networks:
      - backend_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.2
    container_name: logstash
    env_file:
    - .env
    networks:
      - backend_net
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    container_name: kibana
    env_file:
    - .env
    networks:
      - backend_net
    depends_on:
      - elasticsearch
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.2
    container_name: filebeat
    user: root
    command:
      - -e
      - --strict.perms=false
    env_file:
    - .env
    networks:
      - backend_net
    depends_on:
      - elasticsearch

networks:
  backend_net:
