version: '3.4'

services:
  my.ddd.cqrs.temp6.api:
    image: ${DOCKER_REGISTRY-}mydddcqrstemp6api
    container_name: mydddcqrstemp6api
    build:
      context: .
      dockerfile: My.DDD.CQRS.Temp6.Api/Dockerfile
      
  local.azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: localazurite
    command:
      - "azurite"
      - "--queueHost"
      - "0.0.0.0"
      - "--blobHost"
      - "0.0.0.0"
      - "--tableHost"
      - "0.0.0.0"
      - "--disableProductStyleUrl"
