apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-ddd-cqrs-temp6-api-istio.fullname" . }}
  labels:
    {{- include "my-ddd-cqrs-temp6-api-istio.labels" . | nindent 4 }}
    app: {{ include "my-ddd-cqrs-temp6-api-istio.fullname" . }}
    service: {{ include "my-ddd-cqrs-temp6-api-istio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-ddd-cqrs-temp6-api-istio.selectorLabels" . | nindent 4 }}
    app: {{ include "ebp-istio-template.fullname" . }}
