apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "my-ddd-cqrs-temp6-api-istio.fullname" . }}
  labels:
    {{- include "my-ddd-cqrs-temp6-api-istio.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.gateway.name }}
  hosts:
  - {{ .Values.gateway.host }}
  http:
  - match:
    - port: {{ .Values.gateway.httpsPort }}
    route:
    - destination:
        host: {{ include "my-ddd-cqrs-temp6-api-istio.fullname" . }}
        port:
          number: {{ .Values.service.port }}