{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-ddd-cqrs-temp6-api-ingress.serviceAccountName" . }}
  labels:
    {{- include "my-ddd-cqrs-temp6-api-ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
